// ============================================================================
// blueprint/common.js — Shared helpers used by parser, renderer, metadata,
// and markdown modules. String utilities + graph-traversal predicates that
// don't belong to any one stage of the pipeline.
// ============================================================================

// -- String / field extraction ----------------------------------------------

export function matchField(text, field) {
  const re = new RegExp("^\\s*" + field + "=(.+)$", "m");
  const m = text.match(re);
  return m ? m[1].trim() : null;
}

export function extractQuoted(s) {
  if (!s) return "";
  const m = s.match(/"([^"]*)"/);
  return m ? m[1] : s;
}

export function humanize(s) {
  if (!s) return "";
  return s
    .replace(/([a-z])([A-Z])/g, "$1 $2")
    .replace(/([A-Z]+)([A-Z][a-z])/g, "$1 $2")
    .replace(/_/g, " ");
}

// -- UE serialization: block + pin parsing ----------------------------------
// These walk the raw copy/paste text and are format-level (not Blueprint-
// specific): material graphs serialize the same Begin Object / End Object
// blocks and the same CustomProperties Pin lines, so both engines share them.

export function splitTopLevelBlocks(text) {
  // Walk line by line and accumulate top-level Begin Object ... End Object
  // blocks. Increment depth on every Begin Object, decrement on every End
  // Object. When depth returns to zero, the buffered block is complete.
  // Nested blocks (a CustomEvent's UserDefinedPins, a MaterialGraphNode's
  // inner MaterialExpression) stay inside their parent's buffer rather than
  // being misread as top-level nodes.
  const lines = text.split(/\r?\n/);
  const blocks = [];
  let depth = 0;
  let buffer = [];
  for (const line of lines) {
    const trimmed = line.trim();
    if (trimmed.startsWith("Begin Object")) {
      if (depth === 0) buffer = [];
      buffer.push(line);
      depth++;
    } else if (trimmed.startsWith("End Object")) {
      buffer.push(line);
      depth--;
      if (depth === 0) {
        blocks.push(buffer.join("\n"));
        buffer = [];
      }
    } else if (depth > 0) {
      buffer.push(line);
    }
  }
  return blocks;
}

export function parsePinLine(rawInside) {
  // rawInside is the content between CustomProperties Pin ( ... )
  // Properties are comma-separated key=value, but values can contain commas
  // inside parentheses (e.g. LinkedTo=(NodeName GUID,NodeName2 GUID2,)) or
  // inside quotes. Tokenize carefully.
  //
  // IMPORTANT: UE only serializes Direction when it's EGPD_Output. If
  // Direction is absent, the pin is an INPUT. Defaulting to Output would
  // mis-tag every input pin, breaking the has-incoming-exec check and
  // causing downstream nodes to be misdetected as entry nodes.
  const pin = {
    PinId: "",
    PinName: "",
    Direction: "EGPD_Input",
    PinCategory: "",
    PinSubCategory: "",
    PinSubCategoryObject: "",
    ContainerType: "",
    LinkedTo: [],
    DefaultValue: null,
    AutogeneratedDefaultValue: null,
    DefaultObject: null,
    PinFriendlyName: "",
  };
  const tokens = [];
  let cur = "";
  let parenDepth = 0;
  let inQuote = false;
  for (let i = 0; i < rawInside.length; i++) {
    const c = rawInside[i];
    if (c === '"' && rawInside[i - 1] !== "\\") {
      inQuote = !inQuote;
      cur += c;
    } else if (!inQuote && c === "(") {
      parenDepth++;
      cur += c;
    } else if (!inQuote && c === ")") {
      parenDepth--;
      cur += c;
    } else if (!inQuote && parenDepth === 0 && c === ",") {
      tokens.push(cur);
      cur = "";
    } else {
      cur += c;
    }
  }
  if (cur.trim()) tokens.push(cur);

  for (const tok of tokens) {
    const eq = tok.indexOf("=");
    if (eq < 0) continue;
    const key = tok.slice(0, eq).trim();
    const val = tok.slice(eq + 1).trim();

    if (key === "PinId") pin.PinId = val;
    else if (key === "PinName") pin.PinName = val.replace(/^"|"$/g, "");
    else if (key === "Direction") pin.Direction = val.replace(/^"|"$/g, "");
    else if (key === "PinType.PinCategory") pin.PinCategory = val.replace(/^"|"$/g, "");
    else if (key === "PinType.PinSubCategory") pin.PinSubCategory = val.replace(/^"|"$/g, "");
    else if (key === "PinType.PinSubCategoryObject") pin.PinSubCategoryObject = val.replace(/^"|"$/g, "");
    else if (key === "PinType.ContainerType") pin.ContainerType = val.replace(/^"|"$/g, "");
    else if (key === "DefaultValue") pin.DefaultValue = val.replace(/^"|"$/g, "");
    // UE omits DefaultValue when the typed-in literal equals the pin type's
    // generated default (e.g. 0 on a numeric comparison operand), and serializes
    // only AutogeneratedDefaultValue instead. Capture it so literal constants
    // wired into comparison/math pins aren't dropped from the export.
    else if (key === "AutogeneratedDefaultValue") pin.AutogeneratedDefaultValue = val.replace(/^"|"$/g, "");
    // A "self"/Target pin pointing at a class default object (Default__Foo)
    // marks a static library call (KismetMathLibrary.FClamp, ...) — the call has
    // no instance target, so downstream rendering must not prefix it with "Self".
    else if (key === "DefaultObject") pin.DefaultObject = val.replace(/^"|"$/g, "");
    else if (key === "PinFriendlyName") {
      // PinFriendlyName=NSLOCTEXT("ns","key","actual text") - grab the last
      // quoted segment.
      const m = val.match(/"([^"]*)"\s*\)$/);
      if (m) pin.PinFriendlyName = m[1];
    } else if (key === "LinkedTo") {
      const inner = val.replace(/^\(|\)$/g, "");
      const links = inner.split(",").map((s) => s.trim()).filter(Boolean);
      for (const link of links) {
        const parts = link.split(/\s+/);
        if (parts.length >= 2) {
          pin.LinkedTo.push({ nodeName: parts[0], pinId: parts[1] });
        }
      }
    }
  }
  return pin;
}

// Regex for one CustomProperties Pin (...) line. Shared so both engines tokenize
// pins identically. The alternation lets a value carry quoted strings and one
// level of parentheses without the outer match terminating early.
export const PIN_REGEX = /CustomProperties Pin \(((?:[^()"]|"[^"]*"|\([^)]*\))*)\)/g;

// -- Pin / graph predicates -------------------------------------------------

export function isExecPin(p) { return p.PinCategory === "exec"; }

// Whether a node belongs in the exec-flow diagram at all — i.e. the renderer is
// expected to draw a box for it. A node qualifies when it carries at least one
// exec pin (it participates in the execution graph), excluding reroute Knots,
// which are compressed away by resolveThroughKnots and intentionally never
// drawn. Pure data nodes (VariableGet, math ops, Make*) have no exec pins and
// are rendered inline as data sources, so they're not "executable" in this
// sense. Used to diff the inventory's full node count against what the walk
// actually placed, surfacing exec nodes the traversal silently skipped.
export function isExecutableNode(node) {
  if (node.nodeClass === "K2Node_Knot") return false;
  return node.pins.some(isExecPin);
}

export function hasIncomingExec(node) {
  for (const p of node.pins) {
    if (!isExecPin(p) || p.Direction !== "EGPD_Input") continue;
    if (p.LinkedTo.length > 0) return true;
  }
  return false;
}

// Event-like classes that act as graph entry points. Enhanced Input and the
// legacy input nodes belong here too — they're authored at the top of an event
// graph and the user expects them surfaced as starting points, not as orphans.
const ENTRY_NODE_CLASSES = new Set([
  "K2Node_Event",
  "K2Node_CustomEvent",
  "K2Node_FunctionEntry",
  "K2Node_EnhancedInputAction",
  "K2Node_InputAction",
  "K2Node_InputKey",
  "K2Node_InputAxisEvent",
  "K2Node_InputAxisKeyEvent",
  "K2Node_InputTouch",
  "K2Node_InputVectorAxisEvent",
  "K2Node_ComponentBoundEvent",
  "K2Node_ActorBoundEvent",
]);

export function isEntryNode(node) {
  return ENTRY_NODE_CLASSES.has(node.nodeClass);
}

export function findEntryNodes(nodes) {
  const entries = [];
  for (const n of nodes) {
    if (n.nodeClass === "K2Node_Knot") continue;
    if (isEntryNode(n)) entries.push(n);
  }
  entries.sort((a, b) => (a.posY - b.posY) || (a.posX - b.posX));
  return entries;
}

export function findOrphanNodes(nodes) {
  const orphans = [];
  for (const n of nodes) {
    if (n.nodeClass === "K2Node_Knot") continue;
    if (isEntryNode(n)) continue;
    const hasOut = n.pins.some((p) => isExecPin(p) && p.Direction === "EGPD_Output" && p.LinkedTo.length > 0);
    if (hasOut && !hasIncomingExec(n)) orphans.push(n);
  }
  orphans.sort((a, b) => (a.posY - b.posY) || (a.posX - b.posX));
  return orphans;
}

// Async tasks derived from UBlueprintAsyncActionBase serialize their completion
// branches as dynamic delegate exec outs (OnSuccess / OnFailure / Completed / …)
// rather than a single "then" pin. The renderer needs to treat them as
// branch-like so every completion path is labeled and visible, even when only
// one is wired up.
const ASYNC_NODE_CLASSES = new Set([
  "K2Node_AsyncAction",
  "K2Node_BaseAsyncTask",
  "K2Node_LoadAsset",
  "K2Node_LoadAssetClass",
  "K2Node_LatentGameplayTaskCall",
  "K2Node_LatentAbilityCall",
  "K2Node_LatentOnlineCall",
]);

export function isAsyncNode(node) {
  if (ASYNC_NODE_CLASSES.has(node.nodeClass)) return true;
  // Fallback: any BaseAsyncTask subclass carries a ProxyFactoryFunctionName.
  // Cheap substring check on the raw block avoids missing project-specific
  // async subclasses we don't have on the allow-list.
  return /\bProxyFactoryFunctionName=/.test(node.raw);
}

// Latent UFUNCTIONs (Delay, MoveComponentTo, etc.) compile down to a plain
// CallFunction with a hidden LatentInfo pin of type FLatentActionInfo. They
// look synchronous in the serialized form, but the runtime behavior is
// asynchronous — worth flagging so docs can warn about it.
export function isLatentCallFunction(node) {
  if (node.nodeClass !== "K2Node_CallFunction") return false;
  return node.pins.some((p) => p.PinName === "LatentInfo");
}

// A K2Node_VariableGet with bIsPureGet=False (the "Convert to Validated Get"
// variant) has exec pins. Detect it from the pins rather than the bIsPureGet
// field so we don't have to round-trip through the raw text — a pure get has
// no exec pins, an impure get always does.
export function isImpureVariableGet(node) {
  if (node.nodeClass !== "K2Node_VariableGet") return false;
  return node.pins.some((p) => isExecPin(p));
}

export function isBranchLike(node) {
  return (
    node.nodeClass === "K2Node_IfThenElse" ||
    node.nodeClass === "K2Node_ExecutionSequence" ||
    node.nodeClass === "K2Node_MacroInstance" ||
    node.nodeClass === "K2Node_Composite" ||
    node.nodeClass === "K2Node_MultiGate" ||
    node.nodeClass === "K2Node_EnhancedInputAction" ||
    node.nodeClass === "K2Node_InputAction" ||
    node.nodeClass === "K2Node_InputKey" ||
    node.nodeClass === "K2Node_InputTouch" ||
    node.nodeClass.startsWith("K2Node_Switch") ||
    isAsyncNode(node) ||
    // Validated gets with IsValid / IsNotValid branches need both paths
    // surfaced even when one is left dangling; treating the impure get as
    // branch-like also keeps the connector labeled so the reader can see which
    // exec pin drove the next step.
    isImpureVariableGet(node)
  );
}
